### ISSUE TITLE
Not really related, but...

### ISSUE THREAD

**Issue by CodeGuy92** [leahcimtowebsites/leahcimto.com#19]
Would you be nice enough, and register LankyBox01.leahcimto.com for me?

**Comment by leahcimto** [comment]
ok

**Comment by leahcimto** [comment]
tell me what to put in the dns

**Comment by CodeGuy92** [comment]
what's dns
I've never actually registered a domain before, without the help of others
 LOL!

**Comment by CodeGuy92** [comment]
Can you point lankybox01.leahcimto.com codeguy92.github.io

**Comment by leahcimto** [comment]
sure!

**Comment by CodeGuy92** [comment]
Ok, now i just need to wait :P

**Comment by CodeGuy92** [comment]
Last time i registered a domain, i got really lucky because it turned on like 20 seconds after i pointed it

**Comment by leahcimto** [comment]
sadly i can only point it to codeguy92.github.io. could you move your website repo to codeguy92.github.io? also, make sure you type that domain name (lankybox01.leahcimto.com) in the custom domain section of github pages.

**Comment by CodeGuy92** [comment]
yup

**Comment by leahcimto** [comment]
its working!!

**Comment by CodeGuy92** [comment]
http://lankybox01.leahcimto.com/
:0

**Comment by CodeGuy92** [comment]
Thanks for registering the domain

**Comment by leahcimto** [comment]
anytime :)

**Comment by CodeGuy92** [comment]
https://lankybox01.leahcimto.com/
If i try to go to this link, i am literally redirected to https://lankybox01.leahcimto.com/ban

I somehow banned myself from my own site
help

**Comment by leahcimto** [comment]
wait really
