### ISSUE TITLE
Account System (?)

### ISSUE THREAD

**Issue by CodeGuy92** [leahcimtowebsites/leahcimto.com#7]
Hey, yo! Lanky here.

I was just exploring the web, when i realized-- **AcCoUnT sYsTeM!!!!!1!111!11!11**
So, maybe it would be a cool idea if i could add a custom built forum and account system to your website.

What do you think about this idea?
Lanky

**Comment by leahcimto** [comment]
That sounds cool! I think that would be a fun addition to the site :) I could make a separate repo and invite you as a contributor if you want so I can host it at forums.leahcimto.com or something. @CodeGuy92

**Comment by CodeGuy92** [comment]
Oh, yea! Also i totally forgot that you had a domain name XD. Just create that repo and give me admin access. Also can u give me write access in this repo too? :P

**Comment by CodeGuy92** [comment]
And maybe instead of storing images in the repo, create another repo called cdn and store all the media there? And it could be accessed at cdn.leahcimto.com? Idk i'm just spitting some ideas out of the blue

**Comment by leahcimto** [comment]
Sure! I’ll create those now. I just invited you to this org, you can find the invite in your email (I think).

**Comment by leahcimto** [comment]
If you accept the invite I can give you write access. @CodeGuy92

**Comment by leahcimto** [comment]
Also, I don't think we need a cnd server since we can just host images in the repo.

**Comment by CodeGuy92** [comment]
even if you invite me to the org i still need admin access to each and every repo individually. pls gimme admin access

**Comment by leahcimto** [comment]
@CodeGuy92 Just added you to the editors team. You have write access here and admin on the forum repo.

**Comment by leahcimto** [comment]
@CodeGuy92 I just made the forum repo private, let me know if you lose access.

**Comment by FunctionalMetatable** [comment]
forums yay
