### ISSUE TITLE
Links are 404'd

### ISSUE THREAD

**Issue by FunctionalMetatable** [leahcimtowebsites/leahcimto.com#9]
**Describe the bug**
Links to your projects (e.g /dice) just gives a 404

**suggestion to fix**
make a subdomain, link it to a repo on your main account called `leahcimto.github.io` and your projects will use said subdomain

**Comment by CodeGuy92** [comment]
oh, i'll fix them :)

**Comment by CodeGuy92** [comment]
Oh, the pages were deleted.. oof

**Comment by CodeGuy92** [comment]
@leahcimto

**Comment by CodeGuy92** [comment]
dc97ab2170c0c1bd87cdf3dc9564999a6fe6d6c4

**Comment by FunctionalMetatable** [comment]
Use `http://leahcimto.github.io/dice/` instead for now

**Comment by CodeGuy92** [comment]
Ok hold on

**Comment by CodeGuy92** [comment]
I've also fixed the URLS. Thanks for submitting the issue!

**Comment by CodeGuy92** [comment]
Btw, please stick to the default bug template questions. Don't modify them
